-- MySQL Script generated by MySQL Workbench
-- Tue Oct 20 20:05:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_2020
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_2020` DEFAULT CHARACTER SET utf8 ;
USE `bd_2020` ;

-- -----------------------------------------------------
-- Table `bd_2020`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idinstituicao_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_usuario_instituicao_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_instituicao`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `bd_2020`.`instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`mensagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text_msg` VARCHAR(201) NOT NULL,
  `usuario_id` INT NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_mensagem_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_mensagem_instituicao1_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_mensagem_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_2020`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagem_instituicao1`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `bd_2020`.`instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`sobre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`sobre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sobre_instituicao1_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_sobre_instituicao1`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `bd_2020`.`instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`tramissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`tramissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `sobre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tramissao_sobre1_idx` (`sobre_id` ASC) VISIBLE,
  CONSTRAINT `fk_tramissao_sobre1`
    FOREIGN KEY (`sobre_id`)
    REFERENCES `bd_2020`.`sobre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`sintomas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `sintomascol` VARCHAR(45) NOT NULL,
  `sobre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sintomas_sobre1_idx` (`sobre_id` ASC) VISIBLE,
  CONSTRAINT `fk_sintomas_sobre1`
    FOREIGN KEY (`sobre_id`)
    REFERENCES `bd_2020`.`sobre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`cuidados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`cuidados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `decricao` VARCHAR(200) NOT NULL,
  `sobre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuidados_sobre1_idx` (`sobre_id` ASC) VISIBLE,
  CONSTRAINT `fk_cuidados_sobre1`
    FOREIGN KEY (`sobre_id`)
    REFERENCES `bd_2020`.`sobre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`noticias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `url_imagem` VARCHAR(45) NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_noticias_instituicao1_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_noticias_instituicao1`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `bd_2020`.`instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`tipo_usuario` (
  `tipo` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_2020`.`mapa_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_2020`.`mapa_tipo_usuario` (
  `usuario_id` INT NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  INDEX `fk_mapa_tipo_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_mapa_tipo_usuario_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  PRIMARY KEY (`usuario_id`, `tipo_usuario_id`),
  CONSTRAINT `fk_mapa_tipo_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_2020`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_tipo_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `bd_2020`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
